name: Build and Deploy Svelte App

on:
  push:
    branches:
      - main  # Only deploy from the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 'v20.18.0'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install  # Install dependencies

      - name: Build Svelte app
        run: npm run build  # Build your app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Auth token
          publish_dir: ./public  # Adjust if necessary
